# Generated by Django 5.0 on 2023-12-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasubook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
