# Generated by Django 5.0 on 2023-12-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasubook', '0002_rename_nombre_user_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
