# Generated by Django 5.0 on 2023-12-28 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasubook', '0003_rename_usuario_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ultimo_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
