# Generated by Django 5.0 on 2023-12-28 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasubook', '0005_alter_user_ultimo_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ultimo_ingreso',
            field=models.DateField(default=datetime.date(2023, 12, 28)),
        ),
    ]
